packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.10.4
  rollup: 4.55.1
  tsdown: 0.18.2
  typescript: 5.9.3
  vite: 7.3.0
  vitest: 4.0.16

onlyBuiltDependencies:
  - esbuild
  - lefthook
