import type { Connect } from 'vite'

import { VIRTUAL_MODULE_ID } from '@/constants'
import type { Context } from '@/context'

/** Serves virtual CSS generated by Snow CSS. */
export function serveVirtualCss(ctx: Context): Connect.NextHandleFunction {
  return (req, res, next) => {
    if (req.url === '/' + VIRTUAL_MODULE_ID) {
      const css = ctx.emitAllCss({
        minify: false,
      })

      res.setHeader('Content-Type', 'text/css')
      res.end(css ?? '')

      return
    }

    next()
  }
}
